# Generated by Django 2.1.2 on 2018-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='username',
            field=models.CharField(default='', max_length=55),
        ),
    ]
