# Generated by Django 2.1.2 on 2018-11-14 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polls_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=55),
        ),
    ]
